const KEY='medaka-biyori-v1', $=id=>document.getElementById(id);
let state={started:dateKey(),records:[]},storageBroken=false,effect=null,selectedDate=dateKey(),month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!validState(parsed))throw Error();state=parsed;}}catch{storageBroken=true;}
function toast(message){const open=document.querySelector('dialog[open]');if(open){let notice=open.querySelector('.dialog-notice');if(!notice){notice=document.createElement('p');notice.className='dialog-notice';notice.setAttribute('role','status');open.querySelector('.sheet-heading').after(notice);}notice.textContent=message;}$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
function save(next){if(storageBroken){toast('以前の記録を読み込めないため、上書きを停止しています。');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));state=next;return true;}catch{toast('記録を保存できませんでした。端末の空き容量と保存設定をご確認ください。');return false;}}
function caredDays(){return new Set(state.records.map(r=>dateKey(new Date(r.at))));}
function cleanliness(){const last=state.records.filter(r=>r.type==='water').reduce((a,r)=>Math.max(a,Date.parse(r.at)),0);return last?Math.max(40,100-(Date.now()-last)/3600000):75;}
const defs=[['p','たんぱく質','肉・魚・卵','🥚','#b88957'],['f','脂質','油・バター','🥑','#9a9870'],['c','炭水化物','ごはん・パン','🍙','#b88778']];
$('nutrients').innerHTML=defs.map(([id,label,hint,emoji,color])=>`<div class="nutrient" style="--color:${color}"><label class="nutrient-title" for="${id}"><span class="food-emoji">${emoji}</span><span>${label}<br><small>${hint}</small></span><output id="${id}-value" for="${id}">5</output><small>/ 10</small></label><input id="${id}" aria-label="${label}" type="range" min="1" max="10" step="1" value="5"><div class="range-labels"><span>少なめ</span><span>いつもくらい</span><span>多め</span></div></div>`).join('');
for(const [id] of defs)$(id).oninput=()=>$(id+'-value').value=$(id).value;
function showView(view){$('home-view').hidden=view!=='home';$('diary-view').hidden=view!=='diary';for(const name of ['home','diary']){if(name===view)$('nav-'+name).setAttribute('aria-current','page');else $('nav-'+name).removeAttribute('aria-current');}window.scrollTo({top:0,behavior:'instant'});render();}
$('nav-home').onclick=()=>showView('home');$('nav-diary').onclick=()=>showView('diary');
function openRecord(type){$('record-title').textContent=type==='meal'?'ごはんを記録':'お水を記録';$('meal-panel').hidden=type!=='meal';$('water-panel').hidden=type!=='water';if(type==='meal'){const hour=new Date().getHours();const meal=hour<11?0:hour<16?1:2;document.querySelector(`input[name="meal"][value="${meals[meal]}"]`).checked=true;}$('record-dialog').showModal();$('record-close').focus();}
$('open-meal').onclick=()=>openRecord('meal');$('open-water').onclick=()=>openRecord('water');$('record-close').onclick=()=>$('record-dialog').close();$('settings-open').onclick=()=>{$('settings-dialog').showModal();};$('settings-close').onclick=()=>$('settings-dialog').close();
for(const id of ['record-dialog','settings-dialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const b=$(id).getBoundingClientRect();if(e.clientY<b.top||e.clientX<b.left||e.clientX>b.right)$(id).close();}});
function presets(){document.querySelectorAll('[data-water]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.water===$('water-amount').value)));}
for(const b of document.querySelectorAll('[data-water]'))b.onclick=()=>{$('water-amount').value=b.dataset.water;presets();};$('water-amount').oninput=presets;
let celebrationTimer,finishTimer;
function addRecord(record){const firstToday=!caredDays().has(dateKey());const next={...state,records:[...state.records,{...record,id:crypto.randomUUID(),at:new Date().toISOString()}]};if(!save(next))return false;$('record-dialog').close();selectedDate=dateKey();showView('home');clearTimeout(celebrationTimer);clearTimeout(finishTimer);$('celebration').hidden=true;effect={type:record.type,start:performance.now()};$('tank-caption').textContent=record.type==='meal'?'ごはんだ！ みんな、あつまれ〜':'しゅわしゅわ。新しいお水だね。';if(navigator.vibrate)navigator.vibrate(25);celebrationTimer=setTimeout(()=>{$('celebration-icon').textContent=firstToday?'🌼':'♡';$('celebration-title').textContent=record.type==='meal'?'ごちそうさま！':'ぴかぴか、ありがとう！';$('celebration-sub').textContent=firstToday?'今日のお世話の花が咲いたよ':`${caredDays().size}日ぶんの思い出に、またひとつ。`;$('celebration').hidden=false;},2800);finishTimer=setTimeout(()=>{$('celebration').hidden=true;effect=null;$('tank-caption').textContent='お世話してくれて、ありがとう。';},6500);return true;}
$('meal-panel').onsubmit=e=>{e.preventDefault();if(addRecord({type:'meal',meal:document.querySelector('input[name="meal"]:checked').value,p:+$('p').value,f:+$('f').value,c:+$('c').value})){for(const [id] of defs){$(id).value=5;$(id+'-value').value=5;}}};
$('water-panel').onsubmit=e=>{e.preventDefault();const amount=+$('water-amount').value;if(Number.isInteger(amount)&&amount>0&&amount<=3000)addRecord({type:'water',amount});};
function render(){const today=dateKey(),days=caredDays(),records=state.records.filter(r=>dateKey(new Date(r.at))===today);$('today').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date());$('greeting').textContent=state.records.length?'おかえりなさい。':'はじめまして、こはくです。';$('day-tag').textContent=`いっしょに${Math.max(1,Math.floor((Date.parse(today)-Date.parse(state.started))/86400000)+1)}日目`;$('meal-count').textContent=records.filter(r=>r.type==='meal').length;$('water-total').textContent=records.filter(r=>r.type==='water').reduce((s,r)=>s+r.amount,0).toLocaleString();$('care-days').textContent=days.size;$('diary-days').textContent=days.size+' 日';$('clean-label').textContent=cleanliness()>85?'きらきらのお水':'おだやかなお水';$('flower-strip').replaceChildren();for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=dateKey(d),cared=days.has(key);const div=document.createElement('div');div.className='flower-day'+(cared?' cared':'')+(i===0?' today':'');div.innerHTML=`<span class="bloom" aria-label="${cared?'お世話した日':'まだ記録なし'}">${cared?'🌼':'·'}</span><span>${i===0?'今日':`${d.getMonth()+1}/${d.getDate()}`}</span>`;$('flower-strip').append(div);}$('flower-message').textContent=days.has(today)?'今日の花が咲きました。記録できた自分に、はなまる。':'最初の記録で、今日の花が咲きます。';renderDiary(days);}
function renderDiary(days){$('calendar-title').textContent=`${month.getFullYear()}年 ${month.getMonth()+1}月`;$('calendar').replaceChildren();for(let i=0;i<month.getDay();i++)$('calendar').append(document.createElement('span'));for(let n=1;n<=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();n++){const key=dateKey(new Date(month.getFullYear(),month.getMonth(),n)),b=document.createElement('button');b.type='button';b.disabled=key>dateKey();b.setAttribute('aria-label',`${key}${days.has(key)?' お世話の記録あり':''}`);b.setAttribute('aria-pressed',String(key===selectedDate));b.className=days.has(key)?'cared':'';b.innerHTML=`<span>${n}</span><small>${days.has(key)?'🌼':'·'}</small>`;b.onclick=()=>{selectedDate=key;renderDiary(days);};$('calendar').append(b);}$('next-month').disabled=month.getFullYear()===new Date().getFullYear()&&month.getMonth()===new Date().getMonth();const records=state.records.filter(r=>dateKey(new Date(r.at))===selectedDate).slice().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));$('history-title').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric'}).format(new Date(selectedDate+'T12:00:00'))+'の記録';$('day-summary').textContent=records.length?records.length+'回のお世話':'';$('history-list').replaceChildren();if(!records.length){const li=document.createElement('li');li.className='empty';li.textContent='この日は、まだ記録がありません。自分のペースで、少しずつ。';$('history-list').append(li);}for(const r of records){const li=document.createElement('li'),icon=document.createElement('span'),text=document.createElement('div'),small=document.createElement('small'),time=document.createElement('span'),del=document.createElement('button');icon.className='history-icon';icon.textContent=r.type==='meal'?'🍚':'💧';text.className='history-text';text.textContent=r.type==='meal'?r.meal:`お水 ${r.amount.toLocaleString()} mL`;small.textContent=r.type==='meal'?`たんぱく質 ${r.p} · 脂質 ${r.f} · 炭水化物 ${r.c}`:'水槽をぴかぴかにしました';text.append(small);time.className='history-time';time.textContent=new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit'}).format(new Date(r.at));del.className='delete';del.textContent='取消';del.setAttribute('aria-label',time.textContent+'の記録を取り消す');del.onclick=()=>{if(confirm('この記録を取り消しますか？')&&save({...state,records:state.records.filter(x=>x.id!==r.id)})){render();toast('記録を取り消しました。');}};li.append(icon,text,time,del);$('history-list').append(li);}}
$('prev-month').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render();};$('next-month').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render();};
$('export').onclick=()=>{let data=JSON.stringify(state,null,2);if(storageBroken){data=localStorage.getItem(KEY)||data;}const url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`medaka-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error();const imported=JSON.parse(await file.text());if(!validState(imported))throw Error();if(storageBroken){toast('既存データを保護するため、まずバックアップを保存してください。');return;}const merged=mergeRecords(state,imported),added=merged.added;if(!confirm(`${added}件の記録を追加します。今の記録は残ります。よろしいですか？`))return;if(save(merged.state)){render();$('settings-dialog').close();toast(`${added}件の思い出を戻しました。`);}}catch{toast('このファイルは読み込めません。めだか日和のバックアップを選んでください。');}finally{e.target.value='';}};
$('persist').onclick=async()=>{try{const granted=await navigator.storage?.persist?.();$('persist-status').textContent=granted?'端末による自動削除を防ぐ保存が有効です。手動のデータ削除にはバックアップが必要です。':'保持の許可はChromeが判断します。バックアップもご利用ください。';}catch{$('persist-status').textContent='このブラウザーでは保持設定を変更できません。';}};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install').hidden=true;};
window.addEventListener('storage',e=>{if(e.key===KEY){try{const next=JSON.parse(e.newValue);if(validState(next)){state=next;storageBroken=false;render();}else{storageBroken=true;toast('保存データが変更されました。再読み込みしてください。');}}catch{storageBroken=true;}}});
render();if(storageBroken)toast('以前の記録を読み込めません。上書きせず保護しています。');setInterval(render,60000);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_aquarium_summary',title:'今日のお世話の記録を読む',description:'今日の食事の回数と水分量、お世話した日数を読みます。記録は変更しません。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('引数は空のオブジェクトにしてください。');const records=state.records.filter(r=>dateKey(new Date(r.at))===dateKey());return {date:dateKey(),meals:records.filter(r=>r.type==='meal').length,waterMl:records.filter(r=>r.type==='water').reduce((sum,r)=>sum+r.amount,0),careDays:caredDays().size};}})).catch(()=>{});}catch{}}
